### ISSUE TITLE
TYPO3 11 LTS compatibility

### ISSUE THREAD

**Issue by bjoern86** [FriendsOfTYPO3/rdct#4]
Are there any considerations to make rdct TYPO3 11 LTS compatible?

thx

**Comment by bmack** [comment]
No immediate plans, but if there are Pull Requests making this extension TYPO3 v11 - ready, I'm happy to release a new version. Should be probably an effort of a couple of hours to achieve this.

**Comment by msollmann** [comment]
I would be happy too about a v11 version!

**Comment by abvdveen** [comment]
Me too.

**Comment by linawolf** [comment]
Seems to be solved, can this be closed?
