### ISSUE TITLE
TYPO3 v12 compatibility

### ISSUE THREAD

**Issue by linawolf** [FriendsOfTYPO3/rdct#8]
Is anyone already working on it?

**Comment by RZivaralam** [comment]
I would like to know when will the plugin be compatible with Typo 3 version 12 be released.

**Comment by bmack** [comment]
@RZivaralam @linawolf if there are PRs to make EXT:rdct compatible with v12, I'M happy to review, merge them and then release a new version.

**Comment by RZivaralam** [comment]
> @RZivaralam @linawolf if there are PRs to make EXT:rdct compatible with v12, I'M happy to review, merge them and then release a new version.

i would really appreciate about that

**Comment by SSFGizmo** [comment]
@bmack, @linawolf, @RZivaralam Can you please check this version?
* https://github.com/SSFGizmo/rdct

**Comment by bmack** [comment]
Hey @SSFGizmo ,

thank you.
can you create a PR to this repository?

**Comment by SSFGizmo** [comment]
* https://github.com/FriendsOfTYPO3/rdct/pull/9

**Comment by bmack** [comment]
Released v3.0.0 with TYPO3 v12  support

**Comment by RZivaralam** [comment]
thanks
